version: '3.3'

services:
  verifier:
    image: ghcr.io/eu-digital-identity-wallet/eudi-srv-web-verifier-endpoint-23220-4-kt:latest
    container_name: verifier-backend
    ports:
      - "8080:8080"
    environment:
      VERIFIER_PUBLICURL: "https://verifier.authbound.io"
      VERIFIER_RESPONSE_MODE: "DirectPost"
    restart: unless-stopped
      
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    labels:
      - coolify.managed=true
    networks:
      - coolify

  verifier-ui:
    image: ghcr.io/eu-digital-identity-wallet/eudi-web-verifier:latest
    container_name: verifier-ui
    restart: unless-stopped
    ports:
      - "4300:4300"
    environment:
      - DOMAIN_NAME=""
      - HOST_API="https://verifier.authbound.io"

    depends_on:
      - verifier
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:4300 || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
    labels:
      - caddy=verifier.authbound.io
      # - caddy.reverse_proxy=/api/*{{upstreams verifier-backend:8080}}
      - caddy.reverse_proxy.3=/*{{upstreams verifier-ui:4300}}
      - caddy.reverse_proxy.1=/ui/*{{upstreams verifier-backend:8080}}
      - caddy.reverse_proxy.2=/wallet/*{{upstreams verifier-backend:8080}}
    networks:
      - coolify

networks:
  coolify:
    external: true