version: '3.3'

services:
  verifier:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: verifier-backend
    ports:
      - "8080:8080"
    environment:
      VERIFIER_PUBLICURL: "https://verifier.authbound.io"
      VERIFIER_RESPONSE_MODE: "DirectPost"
    labels:
      # Caddy Docker Proxy labels for routing
      - caddy.enable=true
      - caddy=verifier.authbound.io
      - caddy.handle_order=1
      - caddy.handle=/api/*,/wallet/*,/verifier/*
      - caddy.handle.reverse_proxy=verifier:8080
      - caddy.handle.reverse_proxy.health_path=/actuator/health
      - caddy.handle.reverse_proxy.health_interval=30s

  verifier-ui:
    image: ghcr.io/eu-digital-identity-wallet/eudi-web-verifier:latest
    container_name: verifier-ui
    ports:
      - "4300:4300"
    environment:
      - DOMAIN_NAME="verifier.authbound.io"
      - HOST_API="https://verifier.authbound.io"
    depends_on:
      - verifier
    labels:
      # Caddy Docker Proxy labels for routing
      - caddy.enable=true
      - caddy=verifier.authbound.io
      - caddy.handle_order=0
      - caddy.handle=/*
      - caddy.handle.reverse_proxy=verifier-ui:4300

networks:
  default:
    driver: bridge
  coolify:
    external: true