version: '3.3'

services:
  verifier:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: verifier-backend
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      VERIFIER_PUBLICURL: "${PUBLIC_URL:-https://verifier.authbound.io}"
      VERIFIER_RESPONSE_MODE: "DirectPost"
      SPRING_PROFILES_ACTIVE: "${SPRING_PROFILES_ACTIVE:-prod}"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    labels:
      # Caddy Docker Proxy labels for routing
      - caddy.enable=true
      - caddy=verifier.authbound.io
      - caddy.handle_order=1
      - caddy.handle=/api/*,/wallet/*,/verifier/*
      - caddy.handle.reverse_proxy=verifier:8080
      - caddy.handle.reverse_proxy.health_path=/actuator/health
      - caddy.handle.reverse_proxy.health_interval=30s
    networks:
      - default
      - coolify

  verifier-ui:
    image: ghcr.io/eu-digital-identity-wallet/eudi-web-verifier:latest
    container_name: verifier-ui
    restart: unless-stopped
    ports:
      - "4300:4300"
    environment:
      - DOMAIN_NAME="${DOMAIN_NAME:-verifier.authbound.io}"
      - HOST_API="${PUBLIC_URL:-https://verifier.authbound.io}"
    depends_on:
      - verifier
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:4300 || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
    labels:
      # Caddy Docker Proxy labels for routing
      - caddy.enable=true
      - caddy=verifier.authbound.io
      - caddy.handle_order=0
      - caddy.handle=/*
      - caddy.handle.reverse_proxy=verifier-ui:4300
    networks:
      - default
      - coolify

networks:
  default:
    driver: bridge
  coolify:
    external: true 