version: '3.3'

services:
  verifier:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: verifier-backend
    hostname: verifier-backend
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      VERIFIER_PUBLICURL: "${PUBLIC_URL:-https://verifier.authbound.io}"
      VERIFIER_RESPONSE_MODE: "DirectPost"
      SPRING_PROFILES_ACTIVE: "${SPRING_PROFILES_ACTIVE:-prod}"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    labels:
      - caddy=verifier.authbound.io
      - caddy.reverse_proxy=/api/*,/wallet/*,/ui/* verifier-backend:8080
    networks:
      - coolify
      - default

  verifier-ui:
    image: ghcr.io/eu-digital-identity-wallet/eudi-web-verifier:latest
    container_name: verifier-ui
    hostname: verifier-ui
    restart: unless-stopped
    ports:
      - "4300:4300"
    environment:
      DOMAIN_NAME: ${DOMAIN_NAME:-verifier.authbound.io}
      HOST_API: ${PUBLIC_URL:-https://verifier.authbound.io}
      BASE_PATH: "/"
      PUBLIC_URL: "https://verifier.authbound.io"
      BASE_URL: "https://verifier.authbound.io"
      NODE_ENV: "production"
    depends_on:
      - verifier
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:4300 || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
    labels:
      - caddy=verifier.authbound.io
      - caddy.reverse_proxy=/* verifier-ui:4300
    networks:
      - coolify
      - default

networks:
  default:
    driver: bridge
  coolify:
    external: true 