version: '3.3'

services:
  verifier:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: verifier-backend
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      VERIFIER_PUBLICURL: "https://verifier.authbound.io"
      VERIFIER_RESPONSE_MODE: "DirectPost"
      SERVER_PORT: "8080"
      SPRING_PROFILES_ACTIVE: "${SPRING_PROFILES_ACTIVE:-prod}"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    labels:
      - caddy=verifier.authbound.io
      - caddy.@wallet.path=/wallet/*
      - caddy.handle_path=@wallet
      - caddy.handle_path.reverse_proxy=verifier-backend:8080
      - caddy.@ui.path=/ui/*
      - caddy.handle_path.1=@ui
      - caddy.handle_path.1.reverse_proxy=verifier-backend:8080
      - caddy.@api.path=/api/*
      - caddy.handle_path.2=@api
      - caddy.handle_path.2.reverse_proxy=verifier-backend:8080
    networks:
      - coolify

  verifier-ui:
    image: ghcr.io/eu-digital-identity-wallet/eudi-web-verifier:latest
    container_name: verifier-ui
    restart: unless-stopped
    ports:
      - "4300:4300"
    environment:
      DOMAIN_NAME: "verifier.authbound.io"
      HOST_API: "https://verifier.authbound.io"
      PUBLIC_URL: "https://verifier.authbound.io"
      BASE_URL: "https://verifier.authbound.io"
      NODE_ENV: "production"
    depends_on:
      - verifier
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:4300 || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
    labels:
      - caddy=verifier.authbound.io
      - caddy.@root.path=/*
      - caddy.handle_path.3=@root
      - caddy.handle_path.3.reverse_proxy=verifier-ui:4300
      - caddy.handle.root
      - caddy.handle.root.response.status=404
      - caddy.handle.root.rewrite=* /index.html
    networks:
      - coolify

networks:
  coolify:
    external: true