version: '3.3'

services:
  verifier:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: verifier-backend
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      VERIFIER_PUBLICURL: "https://verifier.authbound.io"
      VERIFIER_RESPONSE_MODE: "DirectPost"
      SERVER_PORT: "8080"
      SPRING_PROFILES_ACTIVE: "${SPRING_PROFILES_ACTIVE:-prod}"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    labels:
      - caddy=verifier.authbound.io
      - caddy.reverse_proxy=/api/* {{upstreams 8080}}
      - caddy.reverse_proxy=/wallet/* {{upstreams 8080}}
      - caddy.reverse_proxy=/ui/* {{upstreams 8080}}
    networks:
      - coolify

  verifier-ui:
    image: ghcr.io/eu-digital-identity-wallet/eudi-web-verifier:latest
    container_name: verifier-ui
    restart: unless-stopped
    ports:
      - "4300:4300"
    environment:
      DOMAIN_NAME: "verifier.authbound.io"
      HOST_API: "https://verifier.authbound.io"
      PUBLIC_URL: "https://verifier.authbound.io"
      BASE_URL: "https://verifier.authbound.io"
      NODE_ENV: "production"
    depends_on:
      - verifier
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:4300 || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
    labels:
      - caddy=verifier.authbound.io
      - caddy.reverse_proxy=/* {{upstreams 4300}}
    networks:
      - coolify

networks:
  coolify:
    external: true 