version: '3.3'

services:
  verifier: # Backend Service
    build:
      context: .
      dockerfile: Dockerfile
    container_name: verifier-backend
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      VERIFIER_PUBLICURL: "https://verifier.authbound.io"
      VERIFIER_RESPONSE_MODE: "DirectPost"
      SERVER_PORT: "8080"
      SPRING_PROFILES_ACTIVE: "${SPRING_PROFILES_ACTIVE:-prod}"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    labels:
      # These labels define specific backend paths
      - caddy=verifier.authbound.io
      - caddy.reverse_proxy=/api/* {{upstreams 8080}}
      - caddy.reverse_proxy=/wallet/* {{upstreams 8080}}
      - caddy.reverse_proxy=/ui/* {{upstreams 8080}} # Assuming /ui/* goes to backend per HAProxy
    networks:
      - coolify

  verifier-ui: # UI Service
    image: ghcr.io/eu-digital-identity-wallet/eudi-web-verifier:latest
    container_name: verifier-ui
    restart: unless-stopped
    ports:
      - "4300:4300"
    environment:
      DOMAIN_NAME: "verifier.authbound.io"
      HOST_API: "https://verifier.authbound.io"
      PUBLIC_URL: "https://verifier.authbound.io"
      BASE_URL: "https://verifier.authbound.io"
      NODE_ENV: "production"
    depends_on:
      - verifier
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:4300 || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
    labels:
      # --- Caddy Labels for verifier-ui (UI) ---
      - caddy=verifier.authbound.io
      # *** CHANGE HERE: Use standard / for catch-all ***
      - caddy.reverse_proxy=/ {{upstreams 4300}}
    networks:
      - coolify

networks:
  coolify:
    external: true